kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: bitcoin-core-pv-claim
spec:
  storageClassName: faster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi

---
# For GKE
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: faster
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd